// Tunnettujen viinialueiden nimet maittain. IT/FR/ES/DE poimittu olemassa
// olevasta datasta (KNOWN_APPELLATIONS + producers-taulu, ks.
// scripts/extract-regions.mjs), duplikaatit siivottu (Champange->Champagne,
// Katalonia/Catalunya->Catalonia). Loput COUNTRIES-rekisterin maat annettu
// käsin (ei poimittu omasta datasta, koska sitä ei näille maille vielä ole).
export const KNOWN_REGIONS: Record<string, string[]> = {
  IT: [
    'Abruzzo',
    'Basilicata',
    'Calabria',
    'Campania',
    'Emilia-Romagna',
    'Friuli-Venezia Giulia',
    'Lazio',
    'Liguria',
    'Lombardia',
    'Marche',
    'Molise',
    'Piemonte',
    'Puglia',
    'Sardinia',
    'Sicilia',
    'Toscana',
    'Trentino-Alto Adige',
    'Umbria',
    "Valle d'Aosta",
    'Veneto',
  ],
  FR: [
    'Alsace',
    'Beaujolais',
    'Bordeaux',
    'Bourgogne',
    'Champagne',
    'Jura',
    'Languedoc',
    'Loire',
    'Provence',
    'Rhône',
    'Roussillon',
  ],
  ES: [
    'Alicante',
    'Almansa',
    'Andalucía',
    'Aragón',
    'Bierzo',
    'Campo de Borja',
    'Castilla y León',
    'Castilla-La Mancha',
    'Catalonia',
    'Galicia',
    'Jerez',
    'Jumilla',
    'Kanariansaaret',
    'La Mancha',
    'Madrid',
    'Méntrida',
    'Murcia',
    'Navarra',
    'Penedès',
    'Priorat',
    'Rías Baixas',
    'Ribera del Duero',
    'Rioja',
    'Rueda',
    'Sierra de Gredos',
    'Somontano',
    'Toro',
    'Valdeorras',
    'Valencia',
  ],
  DE: [
    'Ahr',
    'Baden',
    'Franken',
    'Hessische Bergstraße',
    'Mittelrhein',
    'Mosel',
    'Nahe',
    'Pfalz',
    'Rheingau',
    'Rheinhessen',
    'Saale-Unstrut',
    'Sachsen',
    'Württemberg',
  ],
  CL: [
    'Maipo Valley',
    'Colchagua Valley',
    'Casablanca Valley',
    'Aconcagua Valley',
    'Maule Valley',
    'Curicó Valley',
    'Cachapoal Valley',
    'Limarí Valley',
    'Itata Valley',
    'Bío Bío Valley',
  ],
  AR: [
    'Mendoza',
    'Uco Valley',
    'Luján de Cuyo',
    'Maipú',
    'Salta',
    'Cafayate',
    'San Juan',
    'Neuquén',
    'Río Negro',
    'Patagonia',
  ],
  PT: ['Douro', 'Vinho Verde', 'Dão', 'Bairrada', 'Alentejo', 'Lisbon', 'Setúbal', 'Tejo', 'Madeira', 'Azores'],
  AT: [
    'Wachau',
    'Kamptal',
    'Kremstal',
    'Wagram',
    'Weinviertel',
    'Burgenland',
    'Neusiedlersee',
    'Carnuntum',
    'Thermenregion',
    'Styria',
  ],
  CH: ['Valais', 'Vaud', 'Geneva', 'Ticino', 'Graubünden', 'Neuchâtel', 'Three Lakes', 'Eastern Switzerland'],
  NZ: [
    'Marlborough',
    'Central Otago',
    "Hawke's Bay",
    'Martinborough',
    'Wairarapa',
    'Waipara',
    'Nelson',
    'Gisborne',
    'Auckland',
    'Northland',
  ],
  AU: [
    'Barossa Valley',
    'McLaren Vale',
    'Yarra Valley',
    'Hunter Valley',
    'Margaret River',
    'Clare Valley',
    'Adelaide Hills',
    'Coonawarra',
    'Eden Valley',
    'Tasmania',
  ],
  ZA: [
    'Stellenbosch',
    'Paarl',
    'Franschhoek',
    'Constantia',
    'Swartland',
    'Hemel-en-Aarde',
    'Walker Bay',
    'Robertson',
    'Elgin',
    'Breedekloof',
  ],
  US: [
    'Napa Valley',
    'Sonoma County',
    'Central Coast',
    'Paso Robles',
    'Santa Barbara County',
    'Willamette Valley',
    'Columbia Valley',
    'Walla Walla Valley',
    'Finger Lakes',
    'Long Island',
    'Russian River Valley',
    'Mendocino',
  ],
  GR: ['Santorini', 'Nemea', 'Naoussa', 'Crete', 'Macedonia', 'Peloponnese', 'Attica', 'Cephalonia', 'Rhodes', 'Samos'],
  HU: ['Tokaj', 'Eger', 'Villány', 'Szekszárd', 'Balaton', 'Somló', 'Etyek-Buda', 'Sopron', 'Mátra', 'Neszmély'],
  GE: ['Kakheti', 'Kartli', 'Imereti', 'Racha-Lechkhumi', 'Samegrelo', 'Guria', 'Adjara', 'Meskheti'],
  RO: ['Dealu Mare', 'Moldavia', 'Drăgășani', 'Târnave', 'Miniș-Măderat', 'Banat', 'Crișana', 'Dobrogea'],
  IL: ['Galilee', 'Golan Heights', 'Judean Hills', 'Judean Foothills', 'Samson', 'Shomron', 'Negev'],
  CA: [
    'Okanagan Valley',
    'Niagara Peninsula',
    'Niagara-on-the-Lake',
    'Prince Edward County',
    'Similkameen Valley',
    'Lake Erie North Shore',
    'Fraser Valley',
    'Nova Scotia',
  ],
  BR: [
    'Serra Gaúcha',
    'Vale dos Vinhedos',
    'Campanha Gaúcha',
    'Serra do Sudeste',
    'Vale do São Francisco',
    'Campos de Cima da Serra',
  ],
}

export function getKnownRegions(countryCode: string): string[] {
  return KNOWN_REGIONS[countryCode] ?? []
}
